---
# Source: liferay-aws-infrastructure/templates/elasticsearch.yaml
apiVersion: v1
kind: Secret
metadata:
    name: elasticsearch-connection-details
type: Opaque
stringData:
    ELASTICSEARCH_DEFAULT_PASSWORD_SECRET_NAME: "test-es-elastic-user"
    ELASTICSEARCH_DEFAULT_USERNAME: "elastic"
    ELASTICSEARCH_URL: "http://test-es-http.default.svc:9200"
---
# Source: liferay-aws-infrastructure/templates/elasticsearch.yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
    name: test
    namespace: default
spec:
    http:
        tls:
            selfSignedCertificate:
                disabled: true
    nodeSets:
        -   count: 3
            name: default
            podTemplate:
                spec:
                    containers:
                        -   env:
                                -   name:   ES_JAVA_OPTS
                                    value: "-Xms4g -Xmx4g"
                            name: elasticsearch
                            resources:
                                requests:
                                    cpu: 500m
                                    memory: 4Gi
                                limits:
                                    cpu: 1000m
                                    memory: 8Gi
                    initContainers:
                        -   command:
                                -   sh
                                -   -c
                                -   sysctl -w vm.max_map_count=262144
                            name: configure-memory-map
                            securityContext:
                                privileged: true
                                runAsUser: 0
                        -   command:
                                -   sh
                                -   -c
                                -   |
                                    elasticsearch-plugin \
                                        install \
                                        --batch \
                                        analysis-{icu,kuromoji,smartcn,stempel}
                            name: install-plugins
            volumeClaimTemplates:
                -   metadata:
                        name: elasticsearch-data
                    spec:
                        accessModes:
                            -   ReadWriteOnce
                        resources:
                            requests:
                                storage: 10Gi
    version: 8.12.0
---
# Source: liferay-aws-infrastructure/templates/liferayinfrastructure.yaml
apiVersion: aws.liferay.com/v1alpha1
kind: LiferayInfrastructure
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "-20"
    name: liferay
    namespace: default
spec:
    backup: 
        enabled: false
        region: us-west-2
        rules:
        - retentionDays: 30
          ruleName: daily-backups
          schedule: cron(0 5 * * ? *)
          startWindow: 60
    commonTags:
        EnvironmentId: 
        ProjectId: 
    database: 
        engineVersion: "16.11"
        instanceClass: db.t3.medium
        region: us-west-2
        storageGB: 20
        username: liferay_database_admin
    deletionProtection: false
    environmentId: 
    overlay:
        region: "us-west-2"
    projectId: 
    search:
        elasticsearch: 
            enabled: true
            maxMapCount: 262144
            name: test
            nodeCount: 3
            version: 8.12.0
            volumeSize: 10Gi
        opensearch: 
            engineVersino: OpenSearch_2.15
            instanceCount: 2
            instanceType: t3.small.search
            region: us-west-2
            username: liferay_search_admin
    storage: 
        region: us-west-2
