apiVersion: v1
kind: Pod
metadata:
  name: adminer
  labels:
    name: adminer
spec:
  containers:
  - name: adminer
    image: adminer:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
